### PR TITLE
Cmake build

### LINKED ISSUE #23: Ulfius build on Windows
Hi, I'm looking for a C restful framework, is ulfius windows ok?

### PR DESCRIPTION
**Pull request by babelouest**
And the last one for the day :)

It may fix #23 and #25 at the same time eventually!

@silvioprog , if you want to test this PR too on Windows, that would be much appreciated. I've disabled websocket support for windows for now, because you said that `poll.h` doesn't exist yet. The examples are built too, and the tests succeed on Debian/Ubuntu on my side.

### CODE REVIEW

**Comment by silvioprog** [comment]
Awesome job buddy! 👏 I'll test it as soon as possible.

**Comment by babelouest** [comment]
I'm trying to make ulfius cmake script install orcania and yder automatically from lib folder if the package is not going but I couldn't find how yet, do you have an idea?

**Comment by silvioprog** [comment]
Hello dude.

It can be done with CMake's "ExternalProject_Add()" feature. However, it
would be nice if you could release orcania/yder as "tar.gz" packages (with
respective gpg signatures) using "make dist" from their cmake
building, so ExternalProject_Add()'s
URL would point to their link, something like:

...

ExternalProject_Add(project_yder
  URL "https://github.com/babelouest/yder/yder-${YDER_VERSION}.tar.gz"

(... and some way to test its signature)

...

ExternalProject_Add(project_orcania
  URL "https://github.com/babelouest/orcania/orcania-${ORCANIA_VERSION}
.tar.gz"

(... and some way to test its signature)

...

( I'm busy in a work on the company, but I'm excited to test new
Ulfius building
system :-) )

On Fri, Jan 26, 2018 at 4:49 PM, Nicolas Mora <notifications@github.com>
wrote:

> I'm trying to make ulfius cmake script install orcania and yder
> automatically from lib folder if the package is not going but I couldn't
> find how yet, do you have an idea?
>

-- 
Silvio Clécio

**Comment by silvioprog** [comment]
I have another idea, but I'm not sure it is a best practice. It would be
just download the libraries with "file(DOWNLOAD <url> <file> [<options>...])",
unpacking and using their sources (.c/.h) instead of static/shared
libraries.

On Fri, Jan 26, 2018 at 5:43 PM, silvioprog <silvioprog@gmail.com> wrote:

> Hello dude.
>
> It can be done with CMake's "ExternalProject_Add()" feature. However, it
> would be nice if you could release orcania/yder as "tar.gz" packages (with
> respective gpg signatures) using "make dist" from their cmake building, so ExternalProject_Add()'s
> URL would point to their link, something like:
>
> ...
>
> ExternalProject_Add(project_yder
>   URL "https://github.com/babelouest/yder/yder-${YDER_VERSION}.tar.gz"
>
> (... and some way to test its signature)
>
> ...
>
> ExternalProject_Add(project_orcania
>   URL "https://github.com/babelouest/orcania/orcania-${ORCANIA_VERSION}
> .tar.gz"
>
> (... and some way to test its signature)
>
> ...
>
> ( I'm busy in a work on the company, but I'm excited to test new Ulfius building
> system :-) )
>

-- 
Silvio Clécio

**Comment by silvioprog** [comment]
Hello dude. I'll try to solve it this afternoon. ✌

On Sat, Jan 27, 2018 at 10:43 AM, Nicolas Mora <notifications@github.com>
wrote:

> I'm having some issues to make ExternalProject_Add work properly. Right
> now I try to implement it with Yder on this branch:
> https://github.com/babelouest/yder/tree/cmake
>
> My use of ExternalProject_Add is the following:
>
> include(FindOrcania)
> set(ORCANIA_MIN_VERSION "1.1.1")
> find_package(Orcania ${ORCANIA_MIN_VERSION})
> if (ORCANIA_FOUND)
>   set(LIBS ${ORCANIA_LIBRARIES})
> else ()
>   ExternalProject_Add(Orcania
>                       URL https://github.com/babelouest/orcania/archive/v1.1.1.tar.gz
>                       PREFIX ${CMAKE_CURRENT_BINARY_DIR}/orcania
>                       CONFIGURE_COMMAND "cmake"
>                       BUILD_COMMAND "make"
>                       INSTALL_COMMAND "make install"
>                       )
> endif ()
>
> But this doesn't seem to work as intended. Do you have an idea on how to
> make it build Orcania?
>
-- 
Silvio Clécio

**Comment by babelouest** [comment]
This may be the one we need, I'll wait for your feedbacks on windows install

**Comment by babelouest** [comment]
Hello @silvioprog ,

I'm almost finished the cmake scripts for most of my projects. Before releasing it I would like to make sure ulfius install is correct on Windows. Can you take a look at it and send me feedbacks if you have time?

**Comment by silvioprog** [comment]
Hello dude. Good news! :smiley:

I'll try it as soon as possible in my other machine with Windows 7 and back with feedback ...

**Comment by MoSad85** [comment]
Hello, babelouest,
any news about how to install ulfius on windows?

**Comment by babelouest** [comment]
Hello @MoSad85 ,

The windows build should work now, you need to install it in a [mingw64](https://mingw-w64.org/doku.php) environment with libmicrohttpd and jansson installed, you can read the [INSTALL.md](https://github.com/babelouest/ulfius/blob/master/INSTALL.md) file for more details on the dependencies.

Another way (which I haven't tested though) would be to install Ulfius via [YACP](https://github.com/fd00/yacp/tree/master/ulfius): https://github.com/fd00/yacp

If you have issues with the CMake build, you can open a new issue, since this pull request has been closed

**Comment by MoSad85** [comment]
Hello babelouest,

I tried the last 8 hours to install the library, but without success. The dependencies jansson and libmicrohttpd and try to install the ulfius library with cmake. I get the following console logs on executing this command 
`cmake -G "MinGW Makefiles" -DWITH_CURL=off -DMHD_LIBRARY=C:\ext\libs\microhttpd\libmicrohttpd.dll.a -DMHD_INCLUDE_DIR=C:\ext\libs\microhttpd\include -DJANSSON_LIBRARY=C:\ext\libs\jansson\libjansson.a -DJANSSON_INCLUDE_DIR=C:\ext\libs\jansson\include C:\ext\ulfius-master`

the LOGs:
-- The C compiler identification is GNU 8.1.0
-- Check for working C compiler: C:/MinGW/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - not found
-- Looking for _GNU_SOURCE
-- Looking for _GNU_SOURCE - not found
-- Found mhd: C:/ext/libs/microhttpd/libmicrohttpd-12.dll (found version "0x00095800")
-- Found Jansson: C:/ext/libs/jansson/libjansson.a (found version "2.11")
-- Found Jansson: C:/ext/libs/jansson/libjansson.a (found suitable version "2.11", minimum required is "2.4")

and then nothing happens.
Please help

**Comment by MoSad85** [comment]
Hello babelouest,

i have binding the includes and libs to my eclipse project and added the include line  #include "ulfius/ulfius.h". if i try to build my project i get this error: 

lib\include/ulfius/ulfius.h:50:21: fatal error: pthread.h: No such file or directory

Thank for help

**Comment by babelouest** [comment]
Hello @MoSad85 ,

Before I try to help you, can you open a new issue, detail your how you installed ulfius and explain your issue please?
This thread is about the CMake pull request, I prefer not adding noise in it.

Thanks

**Pull request merged**
