### PR TITLE
Ulfius 2.4

### LINKED ISSUE #63: Different memory functions
I used o_set_alloc_funcs() with my memory allocation functions. All is well, but when microhttpd server tries to close request rises an error.

/lib64/libc.so.6(+0x7f5e4)[0x7f673227b5e4]                                                                                                                                                             
/lib64/libmicrohttpd.so.10(MHD_destroy_response+0x4a)[0x7f672f02e7ba]                                                                                                                                  
/lib64/libmicrohttpd.so.10(MHD_connection_handle_idle+0x251)[0x7f672f0265f1]                                                                                                                           
/lib64/libmicrohttpd.so.10(+0x92cb)[0x7f672f0292cb]

I think that it uses it's own malloc and not my malloc version.
Maybe inside o_set_alloc_funcs you have to comunicate also to microhttpd server that new memory functions as it is done inside ulfius_send_http_streming_request for CURL global_init_mem.

### PR DESCRIPTION
**Pull request by babelouest**
Main features:
- Fix Websocket fragmented messages
- Fix CMake script that installed Orcania twice
- Fix cppcheck warnings
- Add timeout for http connections
- Allow to use MHD_RESPMEM_MUST_COPY for different memory manager, fix #63
- Add websocket client framework
- Add uwsc - Ulfius WebSocket Client - A simple command-line websocket client program

Deep down there's not so much change in the traditional http framework, but a lot of changes in the websocket framework.

### CODE REVIEW

**Comment by babelouest** [comment]
@chipitsine , as a Fedora user, do you think it would be useful to be able to build RPM packages via the CMake script and provide built RPM packages in the release section?

**Comment by chipitsine** [comment]
do you mean cpack --> "pack an rpm yourself" or fedora copr (or other) rpm hosting ?

**Comment by chipitsine** [comment]
as for me, I am ok with building manually

**Comment by babelouest** [comment]
Yes, in the `CMakelists.txt` file, I setup it to build debian and tar.gz packages: https://github.com/babelouest/ulfius/blob/master/CMakeLists.txt#L319

I can also build `RPM` packages as well. With this I could build RPM packages for Fedora and Suse at [every release](https://github.com/babelouest/ulfius/releases), like I do with debian-based distribs.

Anyway, I think I'll do it anyway, that's not a lot of work and it can be useful so...

**Comment by chipitsine** [comment]
Yes, it sounds reasonable

**Pull request merged**
