### PR TITLE
CMakeLists: Align PKGCONF_REQ_PRIVATE required versions

### PR DESCRIPTION
**Pull request by laf0rge**
The minimum version requirements are a bit odd:  At build time of
ulfius, libmicrohttpd ">= 0.9.51" is sufficient, but then a pkg-config
file is installed stating "PKGCONF_REQ_PRIVATE > 0.9.51", i.e.
explicitly excluding 0.9.51 itself.  The same is the case with gnutls
and libmicrohttpd 0.9.53 in case of websockets.

On the other hand, CPACK_DEBIAN_PACKAGE_DEPENDS again states ">=",
so we had two instances where ">=" was sufficient, but only one where
">" was required.

This matters on Debian stretch, where exactly version 0.9.51 of
libmicrohttpd is packaged and hence ulfius builds and gets packaged,
but then one cannot build any applications against ulfius.

### CODE REVIEW

**Comment by laf0rge** [comment]
would be great to tag a patch release (2.5.3.1 or 2.5.4) from 2.5.3 including this patch.  I also have a similar patch against 2.5.2 available.

**Comment by babelouest** [comment]
Hello @laf0rge ,

Thanks for the pull request. Although the current working branch is [2.6](https://github.com/babelouest/ulfius/tree/2.6), I will make the change there instead.

I would rather not release Ulfius 2.5.4 just for this, since Ulfius 2.6 is on the tracks.
Can I ask why you need a new release?

**Comment by laf0rge** [comment]
Hi Nicolas,

On Wed, Apr 03, 2019 at 05:45:42AM -0700, Nicolas Mora wrote:
> Thanks for the pull request. Although the current working branch is [2.6](https://github.com/babelouest/ulfius/tree/2.6), I will make the change there instead.
>
> I would rather not release Ulfius 2.5.4 just for this, since Ulfius 2.6 is on the tracks.
> Can I ask why you need a new release?

I think stable distributions like Debian don't usually switch to new major versions
but rather prefer bug fixes to stable packages only.  As you're maintaining your own
packages in Debian, you must be a Debian developer and know better.

Of course the distributions can carry a related patch themselves, but rather than
making everyone carry a patch, I believe it's worth tagging a patch release.

But hey, it's your project so your call.

-- 
- Harald Welte <laforge@gnumonks.org>           http://laforge.gnumonks.org/
============================================================================
"Privacy in residential applications is a desirable marketing option."
                                                  (ETSI EN 300 175-7 Ch. A6)

**Comment by babelouest** [comment]
I agree, since Ulfius 2.5 is now in Debian Buster, the branch 2.5 will live a long life. Sometimes I forget about ong tesrm support.

I'll take the opportunity to backport some changes from 2.6 though, then I'll release Ulfius 2.5.4 with your changes.

**Pull request merged**
