### PR TITLE
Make CURL dependency optional

### PR DESCRIPTION
**Pull request by gamaral**
Running the command below will produce a version of ulfius without libcurl.

    make WITHOUT_CURL=1

### CODE REVIEW

**Comment by gamaral** [comment]
Not sure if you're interested in this change, feel free to close if you're not.

**Comment by babelouest** [comment]
I get it, you don't like libcurl ;)

I have no problem with disabling libcurl if one don't need it, but I made a similar patch to disable `ulfius_send_smtp_email` here: https://github.com/babelouest/ulfius/issues/2

In that case, can you modify your pull request to make it another opton like the previous patch, by making this option closer to the other one like:

```C
#ifndef ULFIUS_IGNORE_CURL
```

**Comment by gamaral** [comment]
Hehehe, it's not that I don't like it. ;-) It's just that we won't use it, an embedded project ([openrexkit.org](http://openrexkit.org)) building extra dependencies means extra storage, extra build time, etc.

I'll make it match the change set described. :-D G

**Comment by babelouest** [comment]
Hello @gamaral , any update on this PR?

**Comment by gamaral** [comment]
Sorry for the delay, I'll get around to it later tonight. ;-)

**Comment by gamaral** [comment]
Gonna close this, I ended up working around it. :-)

**Comment by babelouest** [comment]
As you wish :)

**Pull request closed without merging**
